import { Observable } from 'tns-core-modules/data/observable';
import { VideoActivityBase } from "../twilio-common";
export declare class VideoActivity implements VideoActivityBase {
    previousAudioMode: any;
    localVideoView: any;
    remoteVideoView: any;
    localVideoTrack: any;
    localAudioTrack: any;
    cameraCapturer: any;
    cameraCapturerCompat: any;
    accessToken: string;
    TWILIO_ACCESS_TOKEN: string;
    room: any;
    previousMicrophoneMute: boolean;
    localParticipant: any;
    audioManager: any;
    private _event;
    private _roomListener;
    private _participantListener;
    participant: any;
    constructor();
    readonly event: Observable;
    startPreview(): Promise<any>;
    addRemoteParticipant(remoteParticipant: any): void;
    prepareLocalMedia(): Promise<any>;
    onError(reason: string): void;
    removeParticipantVideo(videoTrack: any): void;
    removeRemoteParticipant(remoteParticipant: any): void;
    connect_to_room(roomName: string): void;
    addRemoteParticipantVideo(videoTrack: any): void;
    destroy_local_video(): void;
    disconnect(): void;
    cameraListener(): any;
    roomListener(): any;
    participantListener(): any;
    configure_audio(enable: boolean): void;
    requestAudioFocus(): void;
    set_access_token(token: string): void;
    toggle_local_video(): void;
    toggle_local_audio(): void;
}
